changeLogFile=src/main/resources/db/changelog.xml
url=jdbc:postgresql://localhost:5432/edutech
username=postgres
password=admin12
driver=org.postgresql.Driver
classpath=src/main/resources/postgresql-42.7.3.jar
logLevel=debug
defaultSchemaName=public